name: Frotnend Checks
on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  lint-format:
    name: Run ESLint & Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Lint Frontend
        run: |
          cd frontend
          npm run lint

      - name: Prettier Frontend
        run: |
          cd frontend
          npm run style-check
